name: Generate a build and push to another branch

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REACT_APP_GOOGLE_ANALYTICS_ID: G-29PVXGWYQM
    name: Build and Push
    steps:
      - name: git-checkout
        uses: actions/checkout@v3

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build # The build command of your project

      - name: Push
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: build # The branch name where you want to push the assets
          FOLDER: build # The directory where your assets are generated
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # GitHub will automatically add this - you don't need to bother getting a token
          REACT_APP_GOOGLE_ANALYTICS_ID: ${{ env.REACT_APP_GOOGLE_ANALYTICS_ID }} # Accessing the secret
          REACT_APP_EMAILJS_SERVICE_ID: ${{ secrets.REACT_APP_EMAILJS_SERVICE_ID }} # Add your EmailJS service ID
          REACT_APP_EMAILJS_TEMPLATE_ID_CONTACT_FORM: ${{ secrets.REACT_APP_EMAILJS_TEMPLATE_ID_CONTACT_FORM }} # Add your EmailJS template ID
          REACT_APP_EMAILJS_PUBLIC_ID: ${{ secrets.REACT_APP_EMAILJS_PUBLIC_ID }} # Add your EmailJS public ID
          REACT_APP_FIREBASE_API_KEY: ${{secrets.REACT_APP_FIREBASE_API_KEY}}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{secrets.REACT_APP_FIREBASE_AUTH_DOMAIN}}
          REACT_APP_FIREBASE_PROJECT_ID: ${{secrets.REACT_APP_FIREBASE_PROJECT_ID}}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{secrets.REACT_APP_FIREBASE_STORAGE_BUCKET}}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{secrets.REACT_APP_FIREBASE_MESSAGING_SENDER_ID}}
          REACT_APP_FIREBASE_APP_ID: ${{secrets.REACT_APP_FIREBASE_APP_ID}}
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
